### ISSUE TITLE
Deploy fails at redis container app

### ISSUE THREAD

**Issue by torokzs** [Azure-Samples/azure-search-openai-demo-csharp#108]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd up

### Any log messages given by the failure
> Deployment Error Details:
ContainerAppOperationError: Failed to provision revision for container app 'redis'. Error details: Operation expired.

**Comment by wroman-coke** [comment]
This is happening to me either. There's a previous closed issue for this topic saying is due to a timeout issue. I've tried several times with no luck. Always getting the issue described above.

**Comment by davidglassborow** [comment]
yes, me too 
![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/55509/4c3af0be-4741-45cc-a0d6-7974891a2706)

**Comment by Jeroen-VdB** [comment]
I was able to resolve this by reverting back to the latest available version included in [the documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-bicep).
Next, because the `service` and `serviceBind` properties were not recognized, I commented them out and was able to successfully deploy the template. Not sure what these properties do exactly. 

I changed [container-app.bicep](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/infra/core/host/container-app.bicep) as follows:
```bicep
resource app 'Microsoft.App/containerApps@2022-11-01-preview' = {
  name: name
  location: location
  tags: tags
  // It is critical that the identity is granted ACR pull access before the app is created
  // otherwise the container app will throw a provision error
  // This also forces us to use an user assigned managed identity since there would no way to 
  // provide the system assigned identity with the ACR pull access before the app is created
  dependsOn: usePrivateRegistry ? [ containerRegistryAccess ] : []
  identity: {
    type: normalizedIdentityType
    userAssignedIdentities: !empty(identityName) && normalizedIdentityType == 'UserAssigned' ? { '${userIdentity.id}': {} } : null
  }
  properties: {
    managedEnvironmentId: containerAppsEnvironment.id
    configuration: {
      activeRevisionsMode: revisionMode
      ingress: ingressEnabled ? {
        external: external
        targetPort: targetPort
        transport: 'auto'
        corsPolicy: {
          allowedOrigins: union([ 'https://portal.azure.com', 'https://ms.portal.azure.com' ], allowedOrigins)
        }
      } : null
      dapr: daprEnabled ? {
        enabled: true
        appId: daprAppId
        appProtocol: daprAppProtocol
        appPort: ingressEnabled ? targetPort : 0
      } : { enabled: false }
      secrets: secrets
      //service: !empty(serviceType) ? { type: serviceType } : null
      registries: usePrivateRegistry ? [
        {
          server: '${containerRegistryName}.azurecr.io'
          identity: userIdentity.id
        }
      ] : []
    }
    template: {
      //serviceBinds: !empty(serviceBinds) ? serviceBinds : null
      containers: [
        {
          image: !empty(imageName) ? imageName : 'mcr.microsoft.com/azuredocs/containerapps-helloworld:latest'
          name: containerName
          env: env
          resources: {
            cpu: json(containerCpuCoreCount)
            memory: containerMemory
          }
        }
      ]
      scale: {
        minReplicas: containerMinReplicas
        maxReplicas: containerMaxReplicas
      }
    }
  }
}
```

**Comment by giorgiococci** [comment]
@Jeroen-VdB thank you for the work around you proposed, it also solved the same problem for me

**Comment by luisquintanilla** [comment]
Closing this issue since redis is not used for caching in the latest version of the app.
