### ISSUE TITLE
Documentation suggests you can use a cheap Azure Cognitive Search, but you can't

### ISSUE THREAD

**Issue by davidglassborow** [Azure-Samples/azure-search-openai-demo-csharp#109]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

The documentation in the readme suggests you can use a cheap Azure Cognitive Search to test with:

> **Warning**<br>
> By default this sample will create an Azure App Service, Azure Static Web App, and Azure Cognitive Search resource that have a monthly cost, as well as Form Recognizer resource that has cost per document page. **You can switch them to free versions of each of them** if you want to avoid this cost by changing the parameters file under the infra folder (though there are some limits to consider; for example, **you can have up to 1 free Cognitive Search resource per subscription**, and the free Form Recognizer resource only analyzes the first 2 pages of each document.)

I have successfully switched the Form Recogniser to sku F0 to reduce cost.  However trying to use the free cognitive search doesn't work:

> BadRequest: Semantic Search requires the search service be on a Standard or Storage Optimized Tier. Please refer to https://aka.ms/semanticsearchavailability for more details.

This combined with #108 has meant I've burnt quite a bit of money just trying to get his app running successfully 👎 (it took me ages a couple of days to realise `azd down` doesn't clean up properly, and search standard is £200 per month in my region)

### Any log messages given by the failure
> BadRequest: Semantic Search requires the search service be on a Standard or Storage Optimized Tier. Please refer to https://aka.ms/semanticsearchavailability for more details.

### Expected/desired behavior
> Following the documentation works

### OS and Version?
> Windows 10

**Comment by elbruno** [comment]
The docs now includes a step-by-step on how to deploy using a low cost scenario

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/docs/deploy_lowcost.md

Best
