### ISSUE TITLE
DeploymentFailed: BadRequest: NetworkAcls is required for this resource

### ISSUE THREAD

**Issue by lynnaloo** [Azure-Samples/azure-search-openai-demo-csharp#112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

azd up

### Any log messages given by the failure
>

ERROR: deployment failed: error deploying infrastructure: failed deploying: deploying to subscription:

Deployment Error Details:
BadRequest: NetworkAcls is required for this resouce.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

macOS Ventura

### Versions
>

### Mention any other details that might be useful

I was able to resolve this issue with the fix mentioned in this bug report: https://github.com/Azure-Samples/azure-search-openai-demo/issues/133

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TimoRiikonenIF** [comment]
We got this same issue.
Suggested solution also fixed this. Thanks you @lynnaloo

**Comment by Coruscate5** [comment]
The networkAcls line is still missing from the cognitiveservices.bicep file when initializing through azd init

**Comment by luisquintanilla** [comment]
Closing this issue for now. Work and investigations related to NetworkAcls being tracked in #250
