### ISSUE TITLE
Updating/work-with this template for GHA feature.

### ISSUE THREAD

**Issue by zedy-wj** [Azure-Samples/azure-search-openai-demo-csharp#121]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
We are updating this template to support new features in `Github Action`.

For the Github Action feature: We will remove two lines of code on container image and add GHA code after checkout step in the .github/workflow/azure-dev.yml file. (Shown as below)

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/81678720/bfecca87-c3bd-4f79-a674-d01baac0aa59)

@rajeshkamal5050 , @IEvangelist , @jongio for notification.

**Comment by luisquintanilla** [comment]
Closing this issue as dupe. Work tracked in #149
