### ISSUE TITLE
Proposed updates (Sep 2023)

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#123]
There are a few things that we need to update in the application to make deployment more reliable. 

## P0

- [x] #135
- [x] #140
  - [x] #161 
- [x] #137
  - [x] #138
  - [x] #139
  - [x] #136 
- [x] #120
  
### Infra

- [ ] #128
- [ ] #142

## Ingestion

- [ ] #160
- [x] #130
- [x] #132
  - [ ] Add component to Chat page that allows users to upload their own documents
  - [ ] Use PrepareDocs Azure Function endpoint to upload and chat with documents.
- [x] #131

## Documentation

- [ ] #134

### Infra

- [ ] #127

### Backend 

- [x] #168

**Comment by bradygaster** [comment]
My 2C: Amplify PrepareDocs becoming an Azure Function to P0. Then remove that from the deployment-time stuff and add some sort of "upload your doc here" feature that would allow a user to upload a doc, then have the function that processes it and adds it's content to the back-end system a triggered event. So files are uploaded, then immediately added to the model so subsequent questions can be asked as new documents are uploaded.

**Comment by Coruscate5** [comment]
GetChatCompletions is what I came here for - still useful to have this sample but I haven't been able to figure streaming Chat responses through the Blazor API side, would be very useful to see this in the same project given how much difficulty I've had just getting it working

**Comment by LadyNaggaga** [comment]
We may want to build a sample that uses some 3rd partner vector store

**Comment by LadyNaggaga** [comment]
We need to add authentication to this app if plan for people to upload docs. Just to follow best practices.

**Comment by luisquintanilla** [comment]
Closing since P0 items are complete. Pending issues tracked in #174
