### ISSUE TITLE
Unable to deploy within existing resource groups

### ISSUE THREAD

**Issue by davidwboyd** [Azure-Samples/azure-search-openai-demo-csharp#151]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
If you have existing resource groups you are using for testing and experimentation this application fails to deploy and use
existing resource groups.   It fails with:

A resource with the same name cannot be created in location 'eastus2'. Please select a new resource name. (Code: InvalidResourceLocation)

Follow the readme and set each resource group to my common resource group as follows:
azd env set AZURE_SUBSCRIPTION_ID <<Redacted>
azd env set AZURE_RESOURCE_GROUP rg-ParsonsSearch
azd env set AZURE_FORMRECOGNIZER_RESOURCE_GROUP rg-ParsonsSearch
azd env set AZURE_FORMRECOGNIZER_SERVICE cog-fr-parsonssearch
azd env set AZURE_SEARCH_SERVICE_RESOURCE_GROUP rg-ParsonsSearch
azd env set AZURE_SEARCH_SERVICE search-parsons
azd env set AZURE_SEARCH_INDEX idx-oaicsharp
azd env set AZURE_STORAGE_RESOURCE_GROUP rg-ParsonsSearch
azd env set AZURE_STORAGE_ACCOUNT parsonssearch
azd env set AZURE_STORAGE_CONTAINER oaicsharp
azd env set AZURE_OPENAI_RESOURCE_GROUP GPT4
azd env set AZURE_OPENAI_SERVICE GPT4-Preview
azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT GPT4-32K
azd env set AZURE_OPENAI_GPT_DEPLOYMENT GPT4-32K-unfiltered
azd env set AZURE_OPENAI_EMB_DEPLOYMENT Embedding
azd env set BACKEND_URI https://oaicsharp.azurewebsites.net

### Any log messages given by the failure
>

### Expected/desired behavior
>
Ideally the deployment code would identify and reuse the existing resrouces.
This is specifically important for the OpenAI resources which will not allow deployments
beyond certain token limits.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>

### Mention any other details that might be useful
This problem does not exist in the Python version of this example.   I assume it is somewhere down in the
bicep files.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
Related to #127
