### ISSUE TITLE
README architecture diagram does not match deployed infrastructure - Managed Grafana

### ISSUE THREAD

**Issue by lucashuet93** [Azure-Samples/azure-search-openai-demo-csharp#156]
> Please provide us with the following information:
> ---------------------------------------------------------------

The architecture diagram in the README includes references to Managed Grafana, Prometheus, etc. that is somewhat confusing given it is not deployed by the infrastructure or referenced again in the documentation. I might consider updating the architecture diagram or adding a note that explains how the monitoring services are expected to play a role.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
Marking as complete due to recent README / doc changes.
