### ISSUE TITLE
Add Azure Function deployment

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#160]
Currently, the bicep configuration file does not account for the Azure Functions resources in

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/tree/main/app/functions/EmbedFunctions

- [x] Add configuration to deploy Azure Functions component. 
- [x] Output environment variable using *main.bicep* to *.env*

**Comment by luisquintanilla** [comment]
@jongio can you please help with this work item. Thanks.

**Comment by jongio** [comment]
when do you need this by

**Comment by luisquintanilla** [comment]
> when do you need this by

End of week would be ideal. Thanks.

**Comment by luisquintanilla** [comment]
Marking issue as complete.
