### ISSUE TITLE
HTTP 405 when using semantic ranker 

### ISSUE THREAD

**Issue by PhilippTP** [Azure-Samples/azure-search-openai-demo-csharp#169]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> activate "Use semantic ranker for retrieval" in the settings

### Any log messages given by the failure
> HTTP 405 : Method Not Allowed

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
If we activate the semantic ranker in the settings, we get a HTTP 405 message. Are there any settings to be done in the cognitive Search ressource?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by elbruno** [comment]
Please review the current AZD UP deploy process.

We can't reproduce the error, feel free to open a new issue and share more context information.

Best
