### ISSUE TITLE
Modify Azure Cognitive Search from Private Public Preview State

### ISSUE THREAD

**Issue by farzad528** [Azure-Samples/azure-search-openai-demo-csharp#173]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Update README to revise Vector search capabilities in Azure Cognitive Search to no longer require sign up and point to public docs: https://learn.microsoft.com/azure/search/vector-search-overview

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luisquintanilla** [comment]
thanks @farzad528

Vector search is already in `main` and the signup comment has been removed.
