### ISSUE TITLE
Chat HTTP500 Error

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#179]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Open Chat Tab and ask one of the predefined questions

### Expected/desired behavior
> The app generates a response

### OS and Version?
> Windows 11

### Versions
> main

### Mention any other details that might be useful

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/d40042a5-d31b-4091-93ce-3c9d8830c956)

**Comment by luisquintanilla** [comment]
@LittleLittleCloud this happens when I click on the predefined questions. If I type the questions, it works. Thoughts?

**Comment by LittleLittleCloud** [comment]
That's wield,,, can you go to azure resources and check if gdbindex service is available?

**Comment by luisquintanilla** [comment]
> That's wield,,, can you go to azure resources and check if gdbindex service is available?

It is

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/acf5049a-2c01-4224-bd7d-bf6fafd21da4)

**Comment by luisquintanilla** [comment]
Closing. I think this was because I was using an 0301 deployment. Works now.
