### ISSUE TITLE
Citations not displaying

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#181]
![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/70c971bc-c65f-4dd5-a15c-4d8d410234aa)

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/bd8b923e-74be-4803-a598-19ed529dd520)

![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/46974588/681e56d7-c578-42c9-9034-c57aa75dfb06)

**Comment by delicpsyche** [comment]
I have the same issue but it returns citation 40% of times - anybody know whats the issue. I checked the query, Cog Search seems to be  returning document ID/page etc but after its send to OpenAI it does not return any documents.

**Comment by luisquintanilla** [comment]
Marking issue complete. This should've been addressed in the latest changes to the app.
