### ISSUE TITLE
Upgrade to Semantic Kernel 1.0

### ISSUE THREAD

**Issue by aaronpowell** [Azure-Samples/azure-search-openai-demo-csharp#185]
Semantic Kernel 1.0 beta is out - https://devblogs.microsoft.com/semantic-kernel/introducing-the-v1-0-0-beta1-for-the-net-semantic-kernel-sdk/

There's several breaking changes that might impact this application that we need to review.

**Comment by jmatthiesen** [comment]
Thanks for the feedback! FYI that this sample has been updated to SK 1.3 with a recent set of changes.
