### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#193]
Now that auth is enabled, provide a logout button in the UI if the user is logged in. 

https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-microsoft-entra-id?view=aspnetcore-7.0

**Comment by LittleLittleCloud** [comment]
This should already been resolved?

**Comment by luisquintanilla** [comment]
Marking issue as complete.
