### ISSUE TITLE
Error on "azd up"

### ISSUE THREAD

**Issue by Coruscate5** [Azure-Samples/azure-search-openai-demo-csharp#207]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> install azd 1.4.3
> follow steps in instructions
> receive error after azd up: "ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: creating template: failed unmarshalling arm template from json: invalid character 'F' looking for beginning of value"

### Any log messages given by the failure
> as above - debug output from AZD simply prints the entire compiled bicep

### Expected/desired behavior
> doesn't error out

### OS and Version?
> Windows 10

### Versions
> azd 1.4.3
> VS 2022 Preview 17.8 (but, using command line for deploy)
> latest build of this sample app (.NET 8 RC2)

### Mention any other details that might be useful

This I believe has happened before when updating the AZD cli - I figured this out once before, hopefully I can figure again.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Coruscate5** [comment]
I fixed this, and is probably quite esoteric but might want to leave it around - you can close. This is due to AutoRun registry settings for each windows user that has the issue - AutoRun injects itself into the CMD pipeline during bicep compilation (unexpected). Fix is to remove AutoRun for the CLI user

**Comment by luisquintanilla** [comment]
Thanks for the detailed solution description @Coruscate5
