### ISSUE TITLE
prepdocs.ps1 requires .NET 8 to run successfully

### ISSUE THREAD

**Issue by danielstocker** [Azure-Samples/azure-search-openai-demo-csharp#210]
![Image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/9444698/ae2d7716-f999-4b14-8e4a-9d7436eb082a)

When running "azd up" without .NET 8 SDK installed the above error occurs.

The readme of the repo indicates that .NET 7 is required. 
It may need an update.

**Comment by karstenjMSFT** [comment]
yep, docs just got updated.

**Comment by luisquintanilla** [comment]
Marking this issue as resolved since .NET 8 is GA and docs are updated.
