### ISSUE TITLE
Default sort order for chat should be set to "bottom"

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#217]

**Comment by shibbas** [comment]
The default sort for the chat thread is set to add new questions to top. It should probably default to bottom. 

<img width="258" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/26466942/ed6b0538-b4b1-46e1-a254-f816c3ffce95">

**Comment by jmatthiesen** [comment]
Renamed after talking with @luisquintanilla since there is only one bug mentioned in this issue. See linked PR with a fix.
