### ISSUE TITLE
Investigate why cognitive services has networkAcls: Allow

### ISSUE THREAD

**Issue by jongio** [Azure-Samples/azure-search-openai-demo-csharp#219]
networkAcls: Allow was added to cognitive services here:
https://github.com/Azure-Samples/azure-search-openai-demo-csharp/pull/147/files#diff-8a64001dc63e4053382af7bbd6519e074e3a637a9e0a50b5b6e8ca136b4224ce

There's an issue to add it here #129 

We should research the security implications of this and remove if not needed.

**Comment by luisquintanilla** [comment]
Work completed by #236. However, there's still #250 which is related and might require further investigation.
