### ISSUE TITLE
Application insights is disabled by default leading to poor customer debugging experience.

### ISSUE THREAD

**Issue by jongio** [Azure-Samples/azure-search-openai-demo-csharp#221]
This project was updated to not include application insights by default.  When trying to debug an app the user will need to jump through many hoops to enable it.  I recommend reverting to having application insights turned on by default.

https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/infra/core/monitor/monitoring.bicep#L2

**Comment by luisquintanilla** [comment]
To be fixed as part of changes in #216
