### ISSUE TITLE
The specified capacity '30' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) 

### ISSUE THREAD

**Issue by bpw320** [Azure-Samples/azure-search-openai-demo-csharp#229]
when deploying, I got the following:
The specified capacity '30' of account deployment is bigger than available capacity '0' for UsageName 'Tokens Per Minute (thousands) - Text-Embedding-Ada-002'.

according to my deployment, the TPM is 120

Properties:
Model name: text-embedding-ada-002
Model version: 2
Version update policy: Once a new default version is available.
Deployment type: Standard
Content Filter: Default
Tokens per Minute Rate Limit (thousands): 120
Rate limit (Tokens per minute): 120000
Rate limit (Requests per minute): 720

Thanks

**Comment by luisquintanilla** [comment]
Hi @bpw320,

This might be because your subscription doesn't have enough capacity. This document has more details on quotas and limits.

https://learn.microsoft.com/azure/ai-services/openai/quotas-limits
