### ISSUE TITLE
Citations File names are not consistent.

### ISSUE THREAD

**Issue by premsonbaby** [Azure-Samples/azure-search-openai-demo-csharp#249]
![error](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/31508228/550a30b8-11df-4a72-8cbc-edf8245733d8)

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Upload document sources.

### Any log messages given by the failure
When the wrong file name created by system  - "BlobNotFoundThe specified blob does not exist. RequestId:4a678a30-901e-0028-712b-2814d8000000 Time:2023-12-06T10:07:06.2566378Z"

### Expected/desired behavior
The Citations links should show relevant file parts.

### OS and Version?
> Windows 11. 

### Mention any other details that might be useful
It looks like the logic that creates the Citations file link is inconsistent, it creates the correct link sometimes but not always.
Please see the attached image. The actual source file name is "GovernanceManualForPrimarySchools20232027.pdf"

**Comment by elbruno** [comment]
Could not reproduce, please open a new Issue and share more information if the issue persist.

Best
