### ISSUE TITLE
Add MAUI Front-End

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#253]

**Comment by luisquintanilla** [comment]
Created this issue to track work being done. Feel free to add more details. 

cc @lutzroeder @mattleibow

**Comment by lutzroeder** [comment]
@BretJohnson @Eilon @maddymontaquila

**Comment by Eilon** [comment]
PR is here: https://github.com/Azure-Samples/azure-search-openai-demo-csharp/pull/255
