### ISSUE TITLE
Implement Chat protocol for backend

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-demo-csharp#254]
With this work we want to conform our chat protocol to https://github.com/Azure/azureml_run_specification/blob/chat-protocol/specs/chat-protocol/chat-app-protocol.md. The goal is to enable interop between chat frontends and backends.

[Similar work was done](https://github.com/Azure-Samples/azure-search-openai-demo/issues/740) for the Python version of this sample.

Unique to the C# sample we need to decide what we do about our additional "Blazor Clippy"/Voice chat pages. We're also unique from the Python sample in that we use Azure Functions for data ingestion / uploading your own docs and need to consider the impact here.

**Comment by jmatthiesen** [comment]
@luisquintanilla / @JakeRadMSFT FYI that I've updated the description based off of recent discussions. Let's hammer out the details here in this issue.
