### ISSUE TITLE
Add support for GPT-4v

### ISSUE THREAD

**Issue by LittleLittleCloud** [Azure-Samples/azure-search-openai-demo-csharp#257]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Feature overview
- generate image embedding and create indexing for pdf files
  - split document into pages and save as PNG in blob storage
  - generate image embedding for each page using [vectorize-image-api](https://learn.microsoft.com/azure/ai-services/computer-vision/how-to/image-retrieval#call-the-vectorize-image-api)
  - add image embedding field to search index

- Update `ReadRetrievalRead` service to generate answers using GPT-4V
  - When retrieving, create query embedding using [vectorizeText api](https://learn.microsoft.com/en-us/azure/ai-services/computer-vision/how-to/image-retrieval#call-the-vectorize-text-api) and get top-k most related pngs from blob storage
  - Then send retrieved pngs along with query to GPT-4V to generate response.

```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by Coruscate5** [comment]
Just as a cheering section, I'm actively looking forward to this feature - I've been testing GPT4v but we've mostly been focused on data syncing optimization in AI Search, so excited to see some samples on it!

**Comment by luisquintanilla** [comment]
TODO: 

- Document azd env flags:

```bash
azd env set USE_AOAI false
azd env set USE_VISION true
azd env set OPENAI_API_KEY <YOUR-OPENAI-KEY>
```
