### ISSUE TITLE
Lots of Unable to find package issues while running AZD UP

### ISSUE THREAD

**Issue by Rickcau** [Azure-Samples/azure-search-openai-demo-csharp#265]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Install Powershell version 7+
2. Clone the Repo, I used VS Community edition to clone but you use the commands in the doc
3. Launch Powershell version 7+ as administrator
4. Make sure Docker Desktop is running as administrator
5. CD into the directory you use to clone the repo
6. Run azd auth login and select the account to log into Azure with
7. Run azd env new azure-search-openai-demo-csharp
8. Run azd up

### Any log messages given by the failure
(x) Failed: Packaging service function
ERROR: failed packaging service 'function': failing invoking action 'package', dotnet publish on project 'C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj' failed: exit code: 1, stdout: MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.AI.FormRecognizer. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.Search.Documents. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.Storage.Blobs. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.AI.OpenAI. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.Storage.Files.Shares. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Azure.Storage.Queues. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Microsoft.Azure.Functions.Worker.Extensions.Storage. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Microsoft.Azure.Functions.Worker.Sdk. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Microsoft.Azure.Functions.Worker. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Microsoft.Extensions.Azure. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Microsoft.Extensions.Configuration.UserSecrets. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj : error NU1101: Unable to find package Pinecone.NET. No packages exist with this id in source(s): C:\Program Files\dotnet\library-packs, Microsoft Visual Studio Offline Packages
  Restored C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\shared\Shared\Shared.csproj (in 122 ms).
  Failed to restore C:\Users\rickcau.NORTHAMERICA\OneDrive - Microsoft\Documents\GitHub_Repro\ai-rag-blazor\app\functions\EmbedFunctions\EmbedFunctions.csproj (in 158 ms).
, stderr:

### Expected/desired behavior
>I expect the azd up command to deploy the solution without error

### OS and Version?
> Window 11

### Versions
> latest version

### Mention any other details that might be useful
Docker Desktop version 4.19, it's working fine as I have two containers running.  I am using WSL 2 with Ubuntu

We really need a super simple way to deploy this using both Docker and without.  Our customers need the ability to standup these solutions as quickly as possible and honestly, leveraging containers often gets in the way of our customers being able to quick experiment with AI tech and the different patterns that this solution demonstrates.

**Comment by Porkechebure** [comment]
The whole setup of this stuff is stupid as hell.
Even by reading the .md file I knew it was going to be troublesome, without even launchign the commands.

Getting same:

> ERROR: current working directory is not a project or service directory. Specify a service name to package a service, or specify --all to package all services

I ran all the various environment setups for setting my own resources on the AI portal:

> Run azd env set AZURE_OPENAI_SERVICE {Name of existing OpenAI service}
> Run azd env set AZURE_OPENAI_RESOURCE_GROUP {Name of existing resource group that OpenAI service is provisioned to}
> Run azd env set AZURE_OPENAI_CHATGPT_DEPLOYMENT {Name of existing ChatGPT deployment}. Only needed if your ChatGPT deployment is not the default 'chat'.
> Run azd env set AZURE_OPENAI_EMBEDDING_DEPLOYMENT {Name of existing embedding model deployment}. Only needed if your embedding model deployment is not the default embedding.
> Run azd up

To receive this crap.
Moreover IT TOTALLY IGNORED everything I set in the environment (active azd environment) to just ask me:

-  Select an Azure Subscription to use
-  Select an Azure location to use

The whole bicep/azd thing is a weak excuse and a failed attempt to copy docker in a much more verbose and inefficient way and this is the result.
You can't even run a simple test app by following their own tutorial step by step.


Now it's stuck like that.

DO something and make the whole thing, expecially the names on the AI portal more clea.
It's a whole rambling crap between deployment/cognitive service/embedding service/project/compute instances and I can keep goint. It's literally a crappy blob of confusing terms weakly linked togheter.

**Comment by LittleLittleCloud** [comment]
@Rickcau It seems that nuget.org official feed is not available in your configuration, maybe consider adding that?

You can add a feed either in `Nuget.Config` or using the following command
```
dotnet nuget add  source -n nuget https://api.nuget.org/v3/index.json
```
