### ISSUE TITLE
Unable to deploy - missing docker copy 

### ISSUE THREAD

**Issue by rbmathis** [Azure-Samples/azure-search-openai-demo-csharp#283]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>follow instructions using codespaces, encounter error on "azd up" command

### Any log messages given by the failure
> various errors about skipping/not finding 'SharedWebComponents.csproj' Ultimate failure on line 19 of Dockerfile when building MinimalApi.csproj'

### Expected/desired behavior
> solution deploys successfully without error

### OS and Version?
> Codespaces

### Versions
>

### Mention any other details that might be useful
easy fix - just insert COPY ["SharedWebComponents/", "SharedWebComponents/"] on line 15 before the RUN dotnet restore
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LittleLittleCloud** [comment]
Thanks for addressing this issue. It has been resolved by #260

**Comment by achrafbenalaya** [comment]
@LittleLittleCloud This change was not merged into the main branch, leading to an error during the Docker file build process.
well seen @rbmathis

**Comment by LittleLittleCloud** [comment]
@achrafbenalaya merged
