### ISSUE TITLE
prepdocs.sh has missing `fi`

### ISSUE THREAD

**Issue by SvenAelterman** [Azure-Samples/azure-search-openai-demo-csharp#288]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> `azd up`

### Any log messages given by the failure
> ./scripts/prepdocs.sh: 50: Syntax error: "else" unexpected (expecting "fi")

### Expected/desired behavior
> Deployment is successful.

### OS and Version?
> Windows 11

**Comment by elbruno** [comment]
Fixed on the latest version
