### ISSUE TITLE
Search service SKU

### ISSUE THREAD

**Issue by matthewjward** [Azure-Samples/azure-search-openai-demo-csharp#302]
Does the sku for the Search service need to be 'standard' (i.e. Standard S1)? Is quite an expensive resource at that sku, could maybe drop the default to Basic?

Thanks

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N/A

### Any log messages given by the failure
> N/A

### Expected/desired behavior
> N/A

### OS and Version?
> N/A

### Versions
> Latest

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tjoudeh** [comment]
Basic should work, but you can't use the free tier as Managed identity is not supported with the free tier.

**Comment by elbruno** [comment]
There is a doc explaining how to run this in low cost mode that may help!
https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/docs/deploy_lowcost.md

Best
