### ISSUE TITLE
After Running "PrepareDocs.dll" its getting stuck

### ISSUE THREAD

**Issue by AkashDoke** [Azure-Samples/azure-search-openai-demo-csharp#308]
![Screenshot 2024-04-02 174518](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/76030891/abc94a95-9ab8-495e-8ba6-a552335755d6)

**Comment by elbruno** [comment]
Could not reproduce, please open a new Issue and share more information if the issue persist.

Best
