### ISSUE TITLE
Connecting on docker doesn't work.

### ISSUE THREAD

**Issue by Riya-Chaudhary-dev** [Azure-Samples/azure-search-openai-demo-csharp#310]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Connecting on docker doesn't work.

### Any log messages given by the failure
>
![image](https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/55593673/1dc26c19-a209-4f39-99ae-cfab14acd546)

### OS and Version?
> Windows 10

**Comment by elbruno** [comment]
Could not reproduce.

Please open a new Issue if the problem persists

Best
