### ISSUE TITLE
ERROR: error executing step command 'package --all': failed packaging service 'web': failing invoking action 'package', parsing source container image: empty image URL provided

### ISSUE THREAD

**Issue by jodyford-msft** [Azure-Samples/azure-search-openai-demo-csharp#316]
### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd init -t azure-search-openai-demo-csharp
> azd env new azure-search-openai-demo-csharp
> azd up

### Any log messages given by the failure
> No

### Expected/desired behavior
> this should not be required if we're creating a new OpenAI resource, right?

### OS and Version?
> macOS (Sonoma)

### Versions
> 14.4 (23E214)

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jodyford-msft** [comment]
docker daemon not running.  please close

**Comment by jodyford-msft** [comment]
ERROR: error executing step command 'package --all': failed packaging service 'web': failing invoking action 'package', parsing source container image: empty image URL provided

**Comment by elbruno** [comment]
Hi @jodyford-msft 

Is this error still valid? Can you share more about your environment? 

Thanks
