### ISSUE TITLE
azd up requires openAIApiKey infra param? 

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo-csharp#318]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. azd auth login
2. azd up

@achandmsft 

### Any log messages given by the failure
>
```console
@diberry ➜ /workspaces/azure-search-openai-demo-csharp (main) $ azd up
? Enter a new environment name: diberry-dotnet-chat
  (✓) Done: Downloading Bicep
? Select an Azure Subscription to use: 23. Azure Dev Platform Services Content Team (2123cb08-23fa-4a80-afec-4ec9e015433f)
? Select an Azure location to use: 11. (US) East US 2 (eastus2)
? Enter a value for the 'openAIApiKey' infrastructure parameter: [? for help] 
```
### Expected/desired behavior
>
AZD up shouldn't ask for anything other than sub and locations. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Codespaces
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lgmorand** [comment]
I do agree. it ask for it, while it deploys a new OpenAI endpoint

**Comment by KristinBethea** [comment]
Where do we get the openAIApiKey?
It's not part of the demo instructions.

**Comment by lgmorand** [comment]
you can ignore it. the openakey is when you provide your own existing instance. but the azd up will pop up a 3.5gpt and a dedicated openai instance by default, even with the key

**Comment by jaliyaudagedara** [comment]
Related: #324

**Comment by FBoucher** [comment]
It will use an existing OpenAI service with this key if provided. If let empty the provisioning will create an Azure openAI service and use that one.

**Comment by EdwinOtten** [comment]
I ran into the same thing and found out I can just skip the parameter thanks to @FBoucher 🙂.

It would be nice if hint actually says so, so I created a PR to add that to the param description in bicep: 
#340
