### ISSUE TITLE
Citation can't be found in UI/Blob storage

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/azure-search-openai-demo-csharp#319]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. azd auth login
2. azd up
3. Use chat app to ask `What is included in my Northwind Health Plus plan that is not in standard?`
4. Select citation.

<img width="984" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/41597107/61ae9e28-fb70-4147-bb20-4bead65cdc84">

5. Get error

<img width="989" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-demo-csharp/assets/41597107/99c1d110-3093-4f5b-a537-37f7366464c2">

@achandmsft @jmatthiesen 
### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by elbruno** [comment]
Hi @diberry 

In the latest release, we updated all the packages and also worked with the latest AOAI models. 
I double checked the scenario, and it's working now. 

Best
