### ISSUE TITLE
Fail to run `azd up` command

### ISSUE THREAD

**Issue by jianingwang123** [Azure-Samples/azure-search-openai-demo-csharp#344]
**Describe the issue:**
When executing `azd up`  , the error is as follows:
![image](https://github.com/user-attachments/assets/3a413710-2b97-409a-a4ba-5d48785add7e)

**Repro Steps:**

1. Open in GitHub Codespaces.
2. Run `azd auth login`
3. Run `azd up`

**Environment:**

- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespaces, Dev Containers and Windows.

**Expected behavior:**
Run `azd up` successfully.

@jongio and @LittleLittleCloud for notification.

**Comment by elbruno** [comment]
Hi @jianingwang123 

I just tested the deploy from Codespaces and it works fine. 
I've recorded a step by step video to support this: [Deploy from Codespaces](https://youtu.be/TORUsRNimM0)

I may advise you to check your permissions in the Azure subscription that you are using.

Best

**Comment by artemious7** [comment]
The Readme says:
> For the target location, the regions that currently support the model used in this sample are East US or Sweden Central. 

I tried location Sweden Central and got an error when creating the Azure AI Search resource since Semantic Search is not supported in Sweden Central.

The original poster chose East US 2 as the location which may have caused that issue.

**Comment by elbruno** [comment]
Thanks for sharing the details @artemious7 
As you mention Semantic Ranker is not (yet) supported in Sweden Central (https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/docs/deploy_lowcost.md)

Updating the readme to only suggest East US.

Best

**Comment by elbruno** [comment]
> Hi @elbruno This issue may be related to our account. Currently, the account we used could not enable `Allow Blob anonymous access` when creating a `Storage account`, which has led to this issue.
> 
> ![image](https://private-user-images.githubusercontent.com/141212663/365106546-8818a287-10df-4a4d-8078-e4b1470fbc1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDAyMTEsIm5iZiI6MTcyNjQ5OTkxMSwicGF0aCI6Ii8xNDEyMTI2NjMvMzY1MTA2NTQ2LTg4MThhMjg3LTEwZGYtNGE0ZC04MDc4LWU0YjE0NzBmYmMxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQxNTE4MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDViMDdmMjkxOTA1NTU2YmZmMTkwNTY4YmQ2OTNkOTIxNDc5MzhlMzM5ZDIyNDE4NGViMGY4ODBjMjZkZDg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A-pmv3GEse_xAkskCokzkF-iVLryMkgEVrr4hyHcWzo)

Thanks for sharing the details, I'll close the current issue and please submit a new one if you need.
Best
