### ISSUE TITLE
Need Guidance/Support for conversational or context based Chat in RAG

### ISSUE THREAD

**Issue by rajeshbayya** [Azure-Samples/azure-search-openai-demo-csharp#348]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Chatbot needs to answer from the conversational context.
Example:
1. First Message sent to chatbot is {"chatHistory": [{"role": "user", content:"what is trial balance?"}]}
     vector search is performed in Azure Search on "what is trial balance?" and fetches search results.
2. Second user Message sent to chatbot is 
   {"chatHistory": [
      {"role": "user", content:"what is trial balance?"},
      {"role": "assistant", content:"trial balance is financial records etc.."},
      {"role": "user", content:"How to upload it?"},
     ]
   }
  vector search is performed in Azure Search on "How to upload it?" and fetches search results which might not be relevant to "how to upload trial balance". How to add previous topic to replace with "it".
 How to aware of context in Azure Search and fetch relevant search results.
 
I am using Semantic Kernel, Azure Search and Azure OpenAI
### Any log messages given by the failure
>

### Expected/desired behavior
> Azure search should be aware of user conversational context for search in vector search

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>Azure.Search.Documents 11.5.1
>Microsoft.SemanticKernel 10.13.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
@pamelafox @LittleLittleCloud @jmatthiesen @IEvangelist @SvenAelterman @tonybaloney
@FBoucher
Please help in guidance for this scenario

**Comment by pamelafox** [comment]
In azure-search-openai-demo (Python RAG), we include a query rewriting step that would rewrite that second query into a better search. Does this repo include the query rewriting step? I do not know since I'm not a maintainer of this repo. I also am not a Semantic Kernel user.

**Comment by rajeshbayya** [comment]
@pamelafox rewriting step is not present in this repo. I will refer Python RAG. Thank you for Guidance.

**Comment by rajeshbayya** [comment]
Refered python Rag repo
