### ISSUE TITLE
Support lower cost deployment and show Cost tiers

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/azure-search-openai-demo-csharp#350]
I notice there's no pricing tier shown here:
https://github.com/Azure-Samples/azure-search-openai-demo-csharp?tab=readme-ov-file#cost-estimation
Can that include tier so its clear what's free tier versus not?

A related request is to support using env parameters to choose cheaper tiers:
https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/deploy_lowcost.md

This would make the repo easier for developers to deploy in hackathons and workshops.

**Comment by elbruno** [comment]
Thanks for the suggestion @pamelafox 
We added this into the main repo: https://github.com/Azure-Samples/azure-search-openai-demo-csharp/blob/main/docs/deploy_lowcost.md

Best,
Bruno

**Comment by pamelafox** [comment]
Woot, I've linked to that from aka.ms/raghack code samples list. Thanks!
