### ISSUE TITLE
Add support for get-4o-mini

### ISSUE THREAD

**Issue by DFMERA** [Azure-Samples/azure-search-openai-demo-csharp#354]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
> Change the template to accept gpt-4o-mini as a valid name of a model

### Mention any other details that might be useful
I can make the change an PR, if you can assign this to me

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DFMERA** [comment]
I created PR #355 with the change

**Comment by elbruno** [comment]
Thanks @DFMERA , just reviewed and approved the PR!
