### ISSUE TITLE
HTTP 500 internal server error

### ISSUE THREAD

**Issue by emleblanc365** [Azure-Samples/azure-search-openai-demo-csharp#373]
I'm getting 500 internal server error when invoking the chat request. Please let me know what I should be checking in order to provide additional information. 

![http500](https://github.com/user-attachments/assets/756df721-2401-457f-b000-ae8b9cfa70c3)

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by emleblanc365** [comment]
Microsoft.SemanticKernel.HttpOperationException: Rate limit is exceeded. Try again in 2 seconds.
Status: 429 (Too Many Requests)
ErrorCode: 429

Maybe I have reached the max rate for open ai

**Comment by elbruno** [comment]
Hi @emleblanc365 
yes it's seems that you hit the rate limit for openai requests
You can check the details on limits and how to request more here: https://learn.microsoft.com/en-us/azure/ai-services/openai/quotas-limits

Best
